# docker-compose.yml
services:
  postgres:
    image: postgres:15
    network_mode: host  # Add this line
    environment:
      POSTGRES_DB: coves_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      PGPORT: 5433
    volumes:
      - ~/Code/Coves/local_dev_data:/var/lib/postgresql/data