# Test Database Docker Compose Configuration
# This database is specifically for running tests and is isolated from dev/prod
services:
  postgres_test:
    image: postgres:15
    container_name: coves_test_db
    network_mode: host
    environment:
      POSTGRES_DB: coves_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      PGPORT: 5434  # Different port from dev (5433) and prod (5432)
    volumes:
      - ~/Code/Coves/test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d coves_test -p 5434"]
      interval: 5s
      timeout: 5s
      retries: 5